# Generated by Django 5.0.3 on 2024-03-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_financeiro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transacao',
            old_name='usuario',
            new_name='user',
        ),
    ]
